version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_database
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redisdata:/data/redis

volumes:
  redisdata:
    driver: local
